on: [push]

name: AzureCLISampleForFile

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: tun
      run:  |
        pwd
        ls
