on: [push]

name: AzureCLISampleForFile

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: whiteducksoftware/azure-arm-action@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resourceGroupName: ExampleGroup
        templateLocation: azuredeploy.json
        deploymentName: newDeployment
