on: push

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v2
      id: set-result
      with:
        script: return "Hello!"
        result-encoding: string
    - name: Get result
      run: echo "${{steps.set-result.outputs.result}}"
