on: [push]

name: AzureCLISampleForFile

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          script: |
           echo "test successful"
