on: [push]

name: AzureCLISampleForFile

  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      run: echo Hello world $FIRST_NAME
      env:
        FIRST_NAME: Vivek  
         
