on: [push]

name: AzureCLISampleForFile

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Setup environment variables
      run: |
        chmod +x ./configuration.sh
        ./configuration.sh      
    
    - name: Checkout Template Repo
      uses: actions/checkout@master
      with:
        repository: echo $TEMPLATE_REPO_PATH
        path: 'file_path'

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.6.0
        inlineScript: |
          echo $TEMPLATE_REPO_PATH +" 1"
          echo $TEMPLATE_FILE +" 2"
          echo $RESOURCE_GROUP +" 3"
