on: [push]

name: AzureCLISampleForFile

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        repository: 'vivishno/testAction'

    - uses: whiteducksoftware/azure-arm-action@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        resourceGroupName: ExampleGroup
        templateLocation: azuredeploy3.json
        deploymentName: newDeployment2
