on: [push]

name: AzureCLISampleForFile

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    - name: deploy all resources
      id: aml_configure
      uses:  mlopstemplates/templateDeploy@master
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          armtemplate_file: "deploy.json"
          armtemplateparams_file: "deploy.params.json"
          ml_armtemplate_file: "ml_deploy.json"
          ml_armtemplateparams_file: "ml_deploy.params.json" 
          resource_group: "TestGroup"
