on: [push]

name: AzureCLISampleForFile

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    - name: deploy all resources
      id: aml_configure
      uses:  mlopstemplates/templateDeploy@v2
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource_group: "new1"
