on: [push]

name: AzureCLISampleForFile

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: deploy all resources
      id: aml_configure
      uses:  mlopstemplates/templateDeploy 
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource_group: "new1"
